// =============================================================================
// Database Seed Script
// =============================================================================
// Seeds the development database with:
//   - 1 admin user
//   - 2 test merchants (with users, API keys, balances)
//   - 3 sample customers
//
// Usage:
//   npx ts-node prisma/seed.ts
//   npm run seed
// =============================================================================

import { PrismaClient, UserRole, MerchantStatus, ApiKeyType } from '@prisma/client';
import crypto from 'crypto';

const prisma = new PrismaClient();

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Simple SHA-256 hash for seeding purposes.
 *
 * ⚠️  The real application uses bcrypt with 12 salt rounds for password
 * hashing. This function exists only to avoid a bcrypt dependency in the
 * seed script.
 */
function hashPassword(password: string): string {
  // In production: bcrypt.hashSync(password, 12)
  return crypto.createHash('sha256').update(password).digest('hex');
}

/**
 * Generates a deterministic API key for seeding.
 * Format mirrors the real key structure: `{prefix}_{type}_{random}`
 */
function generateApiKey(prefix: string, type: 'live' | 'test'): {
  fullKey: string;
  keyPrefix: string;
  keyHash: string;
} {
  const randomPart = crypto.randomBytes(16).toString('hex');
  const fullKey = `${prefix}_${type}_${randomPart}`;
  const keyPrefix = fullKey.substring(0, 12);
  const keyHash = crypto.createHash('sha256').update(fullKey).digest('hex');
  return { fullKey, keyPrefix, keyHash };
}


// ---------------------------------------------------------------------------
// Seed Data
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  console.log('🌱 Seeding database…\n');

  // =========================================================================
  // 1. Admin User
  // =========================================================================
  const adminUser = await prisma.user.upsert({
    where: { email: 'admin@paymentgateway.com' },
    update: {},
    create: {
      email: 'admin@paymentgateway.com',
      // Hash generated by SHA-256 for seeding; real app uses bcrypt with 12 rounds
      passwordHash: hashPassword('Admin@123'),
      role: UserRole.ADMIN,
      isActive: true,
    },
  });
  console.log(`✅ Admin user created: ${adminUser.email} (${adminUser.id})`);

  // =========================================================================
  // 2. Test Merchant #1 — "Acme Electronics"
  // =========================================================================
  const merchant1User = await prisma.user.upsert({
    where: { email: 'merchant1@acme-electronics.com' },
    update: {},
    create: {
      email: 'merchant1@acme-electronics.com',
      passwordHash: hashPassword('Merchant@123'),
      role: UserRole.MERCHANT,
      isActive: true,
    },
  });

  const demoMerchantId = '11111111-1111-1111-1111-111111111111';
  const merchant1 = await prisma.merchant.upsert({
    where: { userId: merchant1User.id },
    update: { id: demoMerchantId },
    create: {
      id: demoMerchantId,
      userId: merchant1User.id,
      businessName: 'Acme Electronics Pvt. Ltd.',
      businessUrl: 'https://acme-electronics.example.com',
      webhookUrl: 'https://acme-electronics.example.com/webhooks/payments',
      webhookSecret: crypto.randomBytes(32).toString('hex'),
      status: MerchantStatus.ACTIVE,
      feePercentage: 2.0,
      isActive: true,
      metadata: { industry: 'electronics', tier: 'standard' },
    },
  });

  // API Keys for Merchant #1
  const demoApiKey = 'sk_test_demo_1234567890abcdef';
  const demoKeyHash = crypto.createHash('sha256').update(demoApiKey).digest('hex');

  await prisma.apiKey.deleteMany({ where: { merchantId: demoMerchantId } });
  await prisma.apiKey.createMany({
    data: [
      {
        merchantId: demoMerchantId,
        keyPrefix: 'sk_test_demo',
        keyHash: demoKeyHash,
        type: ApiKeyType.TEST,
        label: 'Demo Test Key',
        isActive: true,
      },
    ],
  });

  // Balance for Merchant #1
  await prisma.balance.upsert({
    where: { merchantId: merchant1.id },
    update: {},
    create: {
      merchantId: merchant1.id,
      available: 0,
      pending: 0,
      reserved: 0,
      currency: 'INR',
    },
  });

  console.log(`✅ Merchant #1 created: ${merchant1.businessName} (${merchant1.id})`);
  console.log(`   Demo Test API Key: ${demoApiKey}`);

  // =========================================================================
  // 3. Test Merchant #2 — "QuickMart"
  // =========================================================================
  const merchant2User = await prisma.user.upsert({
    where: { email: 'merchant2@quickmart.com' },
    update: {},
    create: {
      email: 'merchant2@quickmart.com',
      passwordHash: hashPassword('Merchant@456'),
      role: UserRole.MERCHANT,
      isActive: true,
    },
  });

  const merchant2 = await prisma.merchant.upsert({
    where: { userId: merchant2User.id },
    update: {},
    create: {
      userId: merchant2User.id,
      businessName: 'QuickMart Online Services',
      businessUrl: 'https://quickmart.example.com',
      webhookUrl: 'https://quickmart.example.com/api/webhooks',
      webhookSecret: crypto.randomBytes(32).toString('hex'),
      status: MerchantStatus.ACTIVE,
      feePercentage: 1.8,
      isActive: true,
      metadata: { industry: 'e-commerce', tier: 'premium' },
    },
  });

  // API Keys for Merchant #2
  const m2LiveKey = generateApiKey('pk', 'live');
  const m2TestKey = generateApiKey('pk', 'test');

  await prisma.apiKey.createMany({
    data: [
      {
        merchantId: merchant2.id,
        keyPrefix: m2LiveKey.keyPrefix,
        keyHash: m2LiveKey.keyHash,
        type: ApiKeyType.LIVE,
        label: 'Production Key',
        isActive: true,
      },
      {
        merchantId: merchant2.id,
        keyPrefix: m2TestKey.keyPrefix,
        keyHash: m2TestKey.keyHash,
        type: ApiKeyType.TEST,
        label: 'Test Key',
        isActive: true,
      },
    ],
    skipDuplicates: true,
  });

  // Balance for Merchant #2
  await prisma.balance.upsert({
    where: { merchantId: merchant2.id },
    update: {},
    create: {
      merchantId: merchant2.id,
      available: 0,
      pending: 0,
      reserved: 0,
      currency: 'INR',
    },
  });

  console.log(`✅ Merchant #2 created: ${merchant2.businessName} (${merchant2.id})`);
  console.log(`   Live API Key: ${m2LiveKey.fullKey}`);
  console.log(`   Test API Key: ${m2TestKey.fullKey}`);

  // =========================================================================
  // 4. Sample Customers
  // =========================================================================
  const customers = await Promise.all([
    prisma.customer.create({
      data: {
        email: 'rahul.sharma@example.com',
        phone: '+919876543210',
        name: 'Rahul Sharma',
        metadata: { source: 'seed' },
      },
    }),
    prisma.customer.create({
      data: {
        email: 'priya.patel@example.com',
        phone: '+919876543211',
        name: 'Priya Patel',
        metadata: { source: 'seed' },
      },
    }),
    prisma.customer.create({
      data: {
        email: 'amit.kumar@example.com',
        phone: '+919876543212',
        name: 'Amit Kumar',
        metadata: { source: 'seed' },
      },
    }),
  ]);

  console.log(`✅ ${customers.length} sample customers created`);

  // =========================================================================
  // Summary
  // =========================================================================
  console.log('\n────────────────────────────────────────');
  console.log('🎉 Seed completed successfully!');
  console.log('────────────────────────────────────────');
  console.log(`   Users     : 3 (1 admin + 2 merchants)`);
  console.log(`   Merchants : 2`);
  console.log(`   API Keys  : 4 (2 per merchant)`);
  console.log(`   Balances  : 2`);
  console.log(`   Customers : ${customers.length}`);
  console.log('────────────────────────────────────────\n');
}

// ---------------------------------------------------------------------------
// Execute
// ---------------------------------------------------------------------------

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error('❌ Seed failed:', error);
    await prisma.$disconnect();
    process.exit(1);
  });
